//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChurchHistory
    {
        public int idChurchHistory { get; set; }
        public string churchName { get; set; }
        public string pastorName { get; set; }
        public int idPerson { get; set; }
        public int roleInChurch { get; set; }
        public string comments { get; set; }
    
        public virtual CheckListCategory CheckListCategory { get; set; }
        public virtual Person Person { get; set; }
    }
}
