//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.Addresses = new HashSet<Address>();
            this.Campus = new HashSet<Campu>();
        }
    
        public int idCountry { get; set; }
        public string iso_alpha2 { get; set; }
        public string iso_alpha3 { get; set; }
        public Nullable<int> iso_numeric { get; set; }
        public string fips_code { get; set; }
        public string name { get; set; }
        public string capital { get; set; }
        public Nullable<double> areainsqkm { get; set; }
        public Nullable<int> population { get; set; }
        public string continent { get; set; }
        public string tld { get; set; }
        public string currency { get; set; }
        public string currencyName { get; set; }
        public string Phone { get; set; }
        public string postalCodeFormat { get; set; }
        public string postalCodeRegex { get; set; }
        public Nullable<int> geonameId { get; set; }
        public string languages { get; set; }
        public string neighbours { get; set; }
        public string equivalentFipsCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Address> Addresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Campu> Campus { get; set; }
    }
}
