//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int idCurrency { get; set; }
        public string currencyCode { get; set; }
        public string currencyName { get; set; }
        public byte[] currencyImage { get; set; }
    }
}
