//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        public int idNotes { get; set; }
        public string notesDescription { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public string createdBy { get; set; }
        public string modifiedBy { get; set; }
        public int idNoteType { get; set; }
        public int idPerson { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
