//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhoto
    {
        public int idPersonPhotos { get; set; }
        public int idPerson { get; set; }
        public string photoPaths { get; set; }
        public byte[] PhotoBLOB { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
