//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.ChurchHistories = new HashSet<ChurchHistory>();
            this.EmploymentHistories = new HashSet<EmploymentHistory>();
            this.MaritalStatus = new HashSet<MaritalStatu>();
            this.Notes = new HashSet<Note>();
            this.PersonPhotos = new HashSet<PersonPhoto>();
            this.StatusHistories = new HashSet<StatusHistory>();
            this.StudyLevels = new HashSet<StudyLevel>();
            this.Tithes = new HashSet<Tithe>();
            this.Documents = new HashSet<Document>();
            this.Documents1 = new HashSet<Document>();
        }
    
        public int idPerson { get; set; }
        public string memberIdentificationNumber { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public Nullable<System.DateTime> dateOfBirth { get; set; }
        public string sex { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<short> isConverted { get; set; }
        public Nullable<System.DateTime> dateConversion { get; set; }
        public Nullable<short> isBaptized { get; set; }
        public Nullable<System.DateTime> dateBaptism { get; set; }
        public Nullable<int> idprofession { get; set; }
        public Nullable<int> idAddress { get; set; }
        public Nullable<short> isMember { get; set; }
        public Nullable<System.DateTime> dateMembership { get; set; }
        public int idEntryPoint { get; set; }
        public Nullable<System.DateTime> dateWedding { get; set; }
        public Nullable<int> idFamilyRole { get; set; }
        public Nullable<int> idFamilies { get; set; }
        public Nullable<short> isDeceased { get; set; }
        public int idCampus { get; set; }
        public Nullable<int> idMedicalInfo { get; set; }
        public Nullable<System.DateTime> dateEntry { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Campu Campu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChurchHistory> ChurchHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentHistory> EmploymentHistories { get; set; }
        public virtual EntryPoint EntryPoint { get; set; }
        public virtual Family Family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaritalStatu> MaritalStatus { get; set; }
        public virtual MedicalInfo MedicalInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Notes { get; set; }
        public virtual Profession Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPhoto> PersonPhotos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusHistory> StatusHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyLevel> StudyLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tithe> Tithes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        public virtual FamilyRole FamilyRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents1 { get; set; }
    }
}
